// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAe5Xe0-okkCS8i9Nv8RiKpjzHboMVSus',
    appId: '1:272420694448:web:83e250ad255e457a60ce75',
    messagingSenderId: '272420694448',
    projectId: 'branch-task',
    authDomain: 'branch-task.firebaseapp.com',
    storageBucket: 'branch-task.appspot.com',
    measurementId: 'G-YP77QTK796',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmXYvqJy1_Q0k-724o2-NdxT0uJ_zLCg',
    appId: '1:272420694448:android:d90e2a0a739b6cae60ce75',
    messagingSenderId: '272420694448',
    projectId: 'branch-task',
    storageBucket: 'branch-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3OQIMT6s_FG3OpmgHRaNmHftvWvDdze8',
    appId: '1:272420694448:ios:d4265985048e542560ce75',
    messagingSenderId: '272420694448',
    projectId: 'branch-task',
    storageBucket: 'branch-task.appspot.com',
    iosBundleId: 'com.example.branch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3OQIMT6s_FG3OpmgHRaNmHftvWvDdze8',
    appId: '1:272420694448:ios:d4265985048e542560ce75',
    messagingSenderId: '272420694448',
    projectId: 'branch-task',
    storageBucket: 'branch-task.appspot.com',
    iosBundleId: 'com.example.branch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAe5Xe0-okkCS8i9Nv8RiKpjzHboMVSus',
    appId: '1:272420694448:web:8ebf2c8489d694c160ce75',
    messagingSenderId: '272420694448',
    projectId: 'branch-task',
    authDomain: 'branch-task.firebaseapp.com',
    storageBucket: 'branch-task.appspot.com',
    measurementId: 'G-QCJ1SZ1D84',
  );
}
